# Generated by Django 5.1.6 on 2025-03-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_buscar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buscar',
            old_name='nome',
            new_name='nome_filme',
        ),
        migrations.RemoveField(
            model_name='buscar',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='buscar',
            name='duracao',
        ),
        migrations.RemoveField(
            model_name='buscar',
            name='preco',
        ),
    ]
